repos:
  - repo: local
    hooks:
      - id: pylint-clickhouse-connect
        name: pylint (clickhouse_connect)
        entry: pylint
        language: system
        types: [python]
        pass_filenames: true
        files: ^clickhouse_connect/.*\.py$

      - id: pylint-tests
        name: pylint (tests)
        entry: pylint
        language: system
        types: [python]
        pass_filenames: true
        files: ^tests/.*\.py$
