name: ClickHouse CI Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '34 17 * * *'

jobs:
  head:
    runs-on: ubuntu-latest
    name: ClickHouse CI Tests
    env:
      CLICKHOUSE_CONNECT_TEST_DOCKER: 'False'
      CLICKHOUSE_CONNECT_TEST_FUZZ: 50
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install Test Dependencies
        run: pip install -r tests/test_requirements.txt
      - name: Build cython extensions
        run: python setup.py build_ext --inplace
      - name: "Add distribution info"  #  This lets SQLAlchemy find entry points
        run: python setup.py develop

      - name: run ClickHouse Cloud tests
        env:
          CLICKHOUSE_CONNECT_TEST_PORT: 8443
          CLICKHOUSE_CONNECT_TEST_CLOUD: 'True'
          CLICKHOUSE_CONNECT_TEST_HOST: ${{ secrets.INTEGRATIONS_TEAM_TESTS_CLOUD_HOST_SMT }}
          CLICKHOUSE_CONNECT_TEST_PASSWORD: ${{ secrets.INTEGRATIONS_TEAM_TESTS_CLOUD_PASSWORD_SMT }}
          CLICKHOUSE_CONNECT_TEST_JWT_SECRET: ${{ secrets.INTEGRATIONS_TEAM_TESTS_CLOUD_JWT_DESERT_VM_43 }}
        run: pytest tests/integration_tests

      - name: Run ClickHouse Container (LATEST)
        run: CLICKHOUSE_CONNECT_TEST_CH_VERSION=latest docker compose up -d clickhouse
      - name: Run LATEST tests
        run: pytest tests/integration_tests
      - name: remove latest container
        run: docker compose down -v
